[package]
name = "day3"
version = "0.1.0"
edition = "2021"
rust = "1.67.0-nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool="1.0.3"