[package]
name = "day5"
version = "0.1.0"
edition = "2021"
rust = "1.67.0-nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"